### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Dimi-Dun-Morogh** [Dimi-Dun-Morogh/WoW_launcher_Sciter#1]
- [x] - html for account and path settings
- [x]  - ui scale for 2/4k screens
- [x] - persistant app storage
- [x]   functions to edit realmlist/settings file
- [x] build exe and release
- [x] write readme
- [x] - minimize btn
- [ ] - some toast with errors

**Comment by Dimi-Dun-Morogh** [comment]
- [ ] - minimize btn
- [ ] - some toast with errors
